Database migration
EXASOL/database-migration pull request #20
Opened 2021-07-15 10:20 UTC by serdarsuezen

Updated the checking procedure

2021-08-31 15:15 UTC, frschwab commented on teradata_to_exasol.sql
> +    'TERADATA_DB'	-- name of your dataabase connection
```suggestion
    'TERADATA_DB'	-- name of your dataabase connection
```
```suggestion
    'TERADATA_DB'	-- name of your dataabase connection
```
```suggestion
    'TERADATA_DB'	-- name of your dataabase connection
```
```suggestion
    'TERADATA_DB'	-- name of your dataabase connection
```

2021-08-31 15:17 UTC, frschwab commented on teradata_to_exasol.sql
> +    ,'RETAIL_2020'	-- schema filter --> '%' to load all schemas except 'DBC' / '%pub%' to load all schemas like '%pub%'
Just do '%' instead of 'RETAIL_2020' in the example, and also adapt the comment which is wrong for the '%' example.

2021-08-31 15:19 UTC, frschwab commented on teradata_to_exasol.sql
> +    ,true			-- boolean flag to create checking tables
Set to false in the example please. But explain also somewhere what it does (where it creates tables, how many tables - I see in database_migration there is a overview table, whereas in the schema itself it creates multiple tables.
By the way it is a great feature which we should use in the other db migrations, too.

2021-08-31 15:20 UTC, frschwab requested changes
I added some comments in the review.

2021-09-01 12:51 UTC, serdarsuezen commented
Added/adjusted the comments.

2021-09-01 12:53 UTC, serdarsuezen reviewed
applied adjustments

2021-09-07 16:49 UTC, merged